stages:
  - lint
  - build
  - test
  - package
  - doc
  - docker
  - deploy
  - release
  - post-release

variables:
  DOCKER_DRIVER: overlay2
  UV_LINK_MODE: copy

#-----------------
# Lint
#-----------------

lint:
  image: ${REGISTRY_URL}/factory-ci-runner:qgis-release
  stage: lint
  script:
    - uv pip install -r requirements.txt -r requirements/lint.txt
    - make lint
  tags:   
    - factory-plain
  variables:
    UV_NO_SYNC: "true"
    UV_NO_MANAGED_PYTHON: "true"

# ------------------------------
# Build cpp Qgis server extension
# -------------------------------

.build-extensions:
  image: ${REGISTRY_URL}/factory-ci-runner:qgis-${QGIS_FLAVOR}
  stage: build
  script:
    - make -C qjazz-contrib build dist
  environment:
    name: snap
  artifacts:
    paths:
    - "dist/qjazz_contrib-*.whl"
    - "qjazz-contrib/src/qjazz_core/qgis/*.so"
  tags:
  - factory-plain

# XXX We cannot use artifacts with parallel/matrix
build-extensions:3.34:
  extends: .build-extensions
  variables:
    QGIS_FLAVOR: '3.34'
    QJAZZ_NO_BUILD_EXT_INSTALL: '1'


build-extensions:3.40:
  extends: .build-extensions
  variables:
    QGIS_FLAVOR: '3.40'

build-extensions:ltr:
  extends: .build-extensions
  variables:
    QGIS_FLAVOR: 'ltr'

build-extensions:release:
  extends: .build-extensions
  variables:
    QGIS_FLAVOR: 'release'

#-----------------
# Build binaries
#-----------------

.build-binaries:
  image: ${REGISTRY_URL}/factory-ci-runner:rust-${OS_TARGET}
  stage: build
  script:
    - make dist
  environment:
    name: snap
  artifacts:
    paths:
    - "dist/qjazz-*.tar.gz"
    - "dist/qjazz_map-*.whl"
    - "dist/qjazz_rpc-*.whl"
    - "dist/qjazz_processes-*.whl"
  tags:
  - factory-plain
  
build-binaries:
  extends: .build-binaries
  variables:
    OS_TARGET: noble
 
build-binaries-trixie:
  extends: .build-binaries
  variables:
    OS_TARGET: trixie


#-----------------
# Tests
#-----------------

.tests:
  image: ${REGISTRY_URL}/factory-ci-runner:qgis-${QGIS_FLAVOR}
  stage: test
  tags: 
    - factory-plain
  resource_group: qjazz_tests
  script:
    - uv pip install -r requirements.txt -r requirements/tests.txt
    - uv pip install --no-deps -e qjazz-contrib
    - uv pip install --no-deps -e qjazz-server/qjazz-rpc/python
    - uv pip install --no-deps -e qjazz-processes
    - make test
  variables:
    UV_NO_SYNC: "true"
    UV_NO_MANAGED_PYTHON: "true"
    PYTEST_ADDOPTS: "--log-cli-level=info"

tests:release:
  extends: .tests
  dependencies:
      - build-extensions:release
  variables:
    QGIS_FLAVOR: "release"

tests:ltr:
  extends: .tests
  dependencies:
      - build-extensions:ltr
  variables:
    QGIS_FLAVOR: "ltr"

tests:3.40:
  extends: .tests
  dependencies:
      - build-extensions:3.40
  variables:
    QGIS_FLAVOR: "3.40"

tests:3.34:
  extends: .tests
  dependencies:
      - build-extensions:3.34
  variables:
    QGIS_FLAVOR: "3.34"
    QJAZZ_NO_BUILD_EXT_INSTALL: '1'

#-----------------
# Packages
#-----------------

.package:
  image: ${REGISTRY_URL}/factory-ci-runner:fabric-ci
  tags:
  - fabric
  stage: package
  rules:
    - if: $RELEASE_BRANCH == "true"
  script:
    - upload_to_packages_server `ls -1 dist/qjazz-*.tar.gz`  pub/qjazz/$QGIS_FLAVOR/qjazz
    - upload_to_packages_server `ls -1 dist/qjazz_contrib-*.whl`  pub/qjazz/$QGIS_FLAVOR/qjazz-contrib
    - upload_to_packages_server `ls -1 dist/qjazz_processes-*.whl`  pub/qjazz/$QGIS_FLAVOR/qjazz-processes
    - upload_to_packages_server `ls -1 dist/qjazz_map-*.whl`  pub/qjazz/$QGIS_FLAVOR/qjazz-map
    - upload_to_packages_server `ls -1 dist/qjazz_rpc-*.whl`  pub/qjazz/$QGIS_FLAVOR/qjazz-rpc

package:release:
  extends: .package
  dependencies:
      - build-extensions:release
      - build-binaries-trixie
  variables:
    QGIS_FLAVOR: "release"

package:ltr:
  extends: .package
  dependencies:
      - build-extensions:ltr
      - build-binaries
  variables:
    QGIS_FLAVOR: "ltr"

package:3.40:
  extends: .package
  dependencies:
      - build-extensions:3.40
      - build-binaries
  variables:
    QGIS_FLAVOR: "3.40"

package:3.34:
  extends: .package
  dependencies:
      - build-extensions:3.34
      - build-binaries
  variables:
    QGIS_FLAVOR: "3.34"


#-----------------
# Doc
#-----------------

doc-build:
  image: ${REGISTRY_URL}/factory-ci-runner:build-doc
  stage: doc
  script: 
    - make -C doc
    - make -C qjazz-processes/doc html
  tags:
    - factory-plain
  allow_failure: true
  artifacts:
    paths: 
      - doc/build/html
      - doc/doc.manifest
      - qjazz-processes/doc/build/html
      - qjazz-processes/doc/doc.manifest
    expire_in: 1 week
  only:
    refs:
    - tags
    - main

doc-deploy:
  stage: doc
  script:
    - upload_to_doc_server doc/build/html/ library/$CI_PROJECT_NAME/
    - upload_to_doc_server doc/doc.manifest library/$CI_PROJECT_NAME/
    - upload_to_doc_server qjazz-processes/doc/build/html/ library/qjazz-processes/
    - upload_to_doc_server qjazz-processes/doc/doc.manifest library/qjazz-processes/
  allow_failure: true
  needs:
    - doc-build
  tags:
    - libs-doc  
  only:
    refs:
    - tags
    - main

# Docker build
include: '/docker/.gitlab-ci.yml'

  

