[logging]
level = "debug"

[worker] 
service_name="Generic_example"
title="An example of generic service"
description="""
Generic service allow defining generic tasks not 
tied to specific QGIS context.
"""
concurrency=1

