#!/bin/bash

#
# All-In-One server script
#
# Run one worker and http server in the background 
# Configure rpc communication via unix socket so there is no need
# to configure network for both services. 
# Use the same config file for both services.
# 

set -e


function help() {
    echo "Usage:"
    echo "run-full-server [config-file]"
    echo ""
    exit 1
}


if [[ $# -eq 1 ]]; then
    [[ "$1" == "-h" ]] && help
    config_option="-C $1"
fi


export CONF_WORKER__INTERFACES='[{ "listen": "unix:/tmp/py-qgis-worker.sock" }]'
export CONF_BACKENDS__LOCAL__ADDRESS=unix:/tmp/py-qgis-worker.sock
export CONF_BACKENDS__LOCAL__ROUTE=/

# Enable job control
set -m


function cleanup() {
    echo "Terminating jobs"
    kill $(jobs -p)
}

trap cleanup EXIT SIGINT SIGABRT SIGTERM SIGQUIT

# Start worker
qgis-server-rpc serve $config_option &

sleep 2

# Start http server
qgis-server-http serve $config_option &

wait -n 
