
DEPTH=..

include $(DEPTH)/config/config.mk

DIRS= \
	py-qgis-contrib \
	py-qgis-cache \
	py-qgis-worker \
	py-qgis-admin \
	py-qgis-http \
	py-qgis-html \
	py-qgis-scripts \
	py-qgis-processes \
	$(NULL)

include $(topsrcdir)/config/rules.mk

