
[backends.basic]
title = "Basic backends"
host = "qgis-rpc"
route = "/"

[[backends.basic.api]]
endpoint = "wfs3"
name = "Features OGC Api (WFS3)"

[[backends.basic.api]]
endpoint = "features"
name = "WFS3"

[[backends.basic.api]]
endpoint = "lizmap"
name = "Lizmap"
