services:
  qgis-rpc:
    image: 3liz/qjazz:qgis-ltr-eager
    command: ["qjazz-rpc", "serve", "-C", "/etc/qjazz/config.toml" ]
    environment:
      CONF_DISPLAY_XVFB: ON
      # For the lizmap plugin
      QGIS_SERVER_LIZMAP_REVEAL_SETTINGS: yes
    volumes:
    - { type: bind, source: "../../tests/data", target: /qgis-projects } 
    - { type: bind, source: "./config-rpc.toml", target: /etc/qjazz/config.toml } 
  web:
    image: 3liz/qjazz:qgis-ltr-eager
    command: ["qjazz-map", "serve", "-C", "/etc/qjazz/config.toml"]
    environment:
      CONF_LOGGING__LEVEL: debug
    volumes:
    - { type: bind, source: "./config-map.toml", target: /etc/qjazz/config.toml } 
    ports:
    - 127.0.0.1:9080:9080

