services:
  qgis-rpc:
    image: 3liz/qjazz:qgis-ltr-eager
    environment:
      CONF_DISPLAY_XVFB: ON
      QGIS_SERVER_LIZMAP_REVEAL_SETTINGS: yes
    volumes:
    - { type: bind, source: "../../tests/data", target: /qgis-projects } 
    - { type: bind, source: "./config-rpc.toml", target: /home/qgis/config.toml } 
    command: ["qjazz-rpc", "serve", "-C", "/home/qgis/config.toml" ]
  web:
    image: 3liz/qjazz:qgis-ltr-eager
    environment:
      CONF_LOGGING__LEVEL: debug
    volumes:
    - { type: bind, source: "./config-map.toml", target: /home/qgis/config.toml } 
    ports:
    - 127.0.0.1:9080:9080
    command: ["qjazz-map", "serve", "-C", "/home/qgis/config.toml"]

