#-------------
# Docker build
#-------------

.build-docker:
  image: ${REGISTRY_URL}/factory-ci-runner:factory-ci
  stage: docker
  script:
  - make -C docker build deliver FLAVOR=$QGIS_FLAVOR
  - make -C docker build deliver FLAVOR=$QGIS_FLAVOR TARGET=lizcloud
  - make -C docker build-ci deliver-ci FLAVOR=$QGIS_FLAVOR
  - cat $DOCKERPASS | docker login -u 3liz --password-stdin
  - make -C docker push-eager FLAVOR=$QGIS_FLAVOR
  environment:
    name: snap
  artifacts:
    paths:
    - "docker/factory-${QGIS_FLAVOR}.manifest"
    - "docker/factory-${QGIS_FLAVOR}-lizcloud.manifest"
  only:
    refs:
    - tags
    - main
  tags:
  - factory-dind

# XXX Matrix build does not allow using dependencies

build-docker:ltr:
  extends: .build-docker
  dependencies:
      - build-binaries
      - build-extensions:ltr
  variables:
    QGIS_FLAVOR: "ltr"

build-docker:release:
  extends: .build-docker
  dependencies:
      - build-binaries
      - build-extensions:release
  variables:
    QGIS_FLAVOR: "release"

build-docker:3.34:
  extends: .build-docker
  dependencies:
      - build-binaries
      - build-extensions:3.34
  variables:
    QGIS_FLAVOR: "3.34"

#
# No QGIS
#

build-docker:noqgis:
  image: ${REGISTRY_URL}/factory-ci-runner:factory-ci
  stage: docker
  script:
  - make -C docker noqgis-build noqgis-deliver
  - make -C docker noqgis-build noqgis-deliver TARGET=lizcloud
  only:
    refs:
    - tags
    - main
  tags:
  - factory-dind
  artifacts:
    paths:
    - "docker/factory-noqgis.manifest"
    - "docker/factory-noqgis-lizcloud.manifest"

# -----------
# release
# ----------

.release:
  image: ${REGISTRY_URL}/factory-ci-runner:factory-ci
  stage: release
  script:
    - release-image qjazz-$QGIS_FLAVOR
  environment:
    name: production
  only:
    refs:
      - tags
  variables:
    FACTORY_MANIFEST: "docker/factory-${QGIS_FLAVOR}-lizcloud.manifest"
  when: manual
  # See https://about.gitlab.com/blog/2021/05/20/dag-manual-fix/#what-if-i-dont-want-this-new-behavior
  allow_failure: false
  tags:
    - factory-dind

release:release:
  extends: .release
  variables:
    QGIS_FLAVOR: release
  dependencies:
    - build-docker:release

release:ltr:
  extends: .release
  variables:
    QGIS_FLAVOR: ltr
  dependencies:
    - build-docker:ltr

release:3.34:
  extends: .release
  variables:
    QGIS_FLAVOR: "3.34"
  dependencies:
    - build-docker:3.34

#
# No QGIS
#

release:noqgis:
  image: ${REGISTRY_URL}/factory-ci-runner:factory-ci
  stage: release
  script:
    - release-image qjazz-noqgis
  environment:
    name: production
  only:
    refs:
      - tags
  variables:
    FACTORY_MANIFEST: "docker/factory-noqgis-lizcloud.manifest"
  when: manual
  allow_failure: false
  tags:
    - factory-dind
  dependencies:
    - build-docker:noqgis

# ------------------
# push to docker hub
# ------------------

.push:
  image: ${REGISTRY_URL}/factory-ci-runner:factory-ci
  stage: post-release
  script:
    - push-to-docker-hub --clean
  environment:
    name: production
  only:
    refs:
      - tags
  variables:
    FACTORY_MANIFEST: "docker/factory-${QGIS_FLAVOR}.manifest"
  tags:
    - factory-dind

push:release:
  extends: .release
  variables:
    QGIS_FLAVOR: release
  dependencies:
    - build-docker:release

push:ltr:
  extends: .release
  variables:
    QGIS_FLAVOR: ltr
  dependencies:
    - build-docker:ltr

push:3.34:
  extends: .release
  variables:
    QGIS_FLAVOR: "3.34"
  dependencies:
    - build-docker:3.34

push:noqgis:
  image: ${REGISTRY_URL}/factory-ci-runner:factory-ci
  stage: post-release
  script:
    - push-to-docker-hub --clean
  environment:
    name: production
  only:
    refs:
      - tags
  variables:
    FACTORY_MANIFEST: "docker/factory-noqgis.manifest"
  tags:
    - factory-dind
  dependencies:
    - build-docker:noqgis
