#-------------
# Build
#-------------

build-binaries:
  image: ${REGISTRY_URL}/factory-ci-runner:rust-noble
  stage: build
  script:
    - make -C qjazz-server build-release
  environment:
    name: snap
  artifacts:
    paths:
    - "qjazz-server/target/release/qjazz-rpc-bin"
    - "qjazz-server/target/release/qjazz-map-bin"
  only:
    refs:
    - tags
    - main
  tags:
  - factory-plain


.build-docker:
  image: ${REGISTRY_URL}/factory-ci-runner:factory-ci
  stage: docker
  script:
  - make -C docker build deliver FLAVOR=$QGIS_FLAVOR BUILD_TARGET=base
  - make -C docker build-front deliver-front FLAVOR=$QGIS_FLAVOR FRONT_BUILD_TARGET=front
  - cat $DOCKERPASS | docker login -u 3liz --password-stdin
  - make -C docker push-eager FLAVOR=$QGIS_FLAVOR
  environment:
    name: snap
  dependencies:
      - build-binaries
  artifacts:
    paths:
    - "docker/factory.manifest"
    - "docker/front.manifest"
  only:
    refs:
    - tags
    - main
  tags:
  - factory-dind

build-docker:
  extends: .build-docker
  parallel:
    matrix:
    - QGIS_FLAVOR: ['ltr', 'release']
