version: "3.9"
services:

  qgis-rpc:
    image: 3liz/qjazz-services:qgis-ltr-eager
    environment:
      CONF_DISPLAY_XVFB: ON
      CONF_CONFIG_URL__URL: "http://config-server/qgis-rpc.json"
      CONF_RESTORE_CACHE__URL: "http://config-server/cache.json"
      CONF_RESTORE_CACHE__RESTORE_TYPE: "http"
    volumes:
    - { type: bind, source: "../../tests/data", target: /qgis-projects } 
    command: ["qjazz-server-rpc", "serve"]

  web:
    image: 3liz/qjazz-services:qgis-ltr
    environment:
      CONF_CONFIG_URL__URL: "http://config-server/web.json"
    ports:
    - 80:80
    command: ["qjazz-server-http", "serve"]

  # The configuration server 
  config-server:
    image: nginx:alpine
    volumes:
    - type: bind
      source: "${PWD}/configs"
      target: /usr/share/nginx/html
      read_only: true

