
run-map:
	cargo run --bin qjazz-map-bin serve -C ./config-map.toml

run-rpc:
	cargo run --bin qjazz-rpc-bin serve -C ./config-rpc.toml

run-rpc-monitor:
	cargo run --features=monitor --bin qjazz-rpc-bin serve -C ./config-rpc.toml
