services:

  #
  # Processes stack
  #

  processes-worker:
    image: 3liz/qjazz:qgis-ltr-eager
    environment:
      CONF_LOGGING__LEVEL: DEBUG
      CONF_WORKER__BROKER_HOST: rabbitmq
      CONF_WORKER__BACKEND_HOST: redis:6379/0
      CONF_PROCESSING__ADVERTISED_SERVICES_URL: "http://localhost:9180/results/$$jobId/$$name"
    depends_on:
    - rabbitmq
    - redis
    working_dir: /conf
    volumes:
    - { type: bind, source: "./", target: /conf } 
    - { type: bind, source: "../../", target: /src } 
    command: ["qjazz-processes", "worker", "-l", "error","-C", "/conf/worker.toml"]
  
  processes-server:
    image: 3liz/qjazz:qgis-ltr-eager
    ports:
    - 127.0.0.1:9180:9080
    command: ["qjazz-processes", "serve", "-v"]
    environment:
      CONF_EXECUTOR__CELERY__BROKER_HOST: rabbitmq
      CONF_EXECUTOR__CELERY__BACKEND_HOST: redis:6379/0
    depends_on:
    - rabbitmq
    - redis

  rabbitmq:
    image: rabbitmq:3
  redis:
    image: redis:6-alpine
w
  #
  # Map server stack
  #
 
  qgis-rpc:
    image: 3liz/qjazz:qgis-ltr-eager
    environment:
      CONF_DISPLAY_XVFB: ON
      CONF_LOGGING__LEVEL: debug
      CONF_WORKER__NAME: worker
      CONF_WORKER__QGIS__PROJECTS__SEARCH_PATHS: >-
        { 
          "/": "/workdir"
        }
    volumes:
    - { type: bind, source: "./__workdir__", target: /workdir } 
    command: ["qjazz-rpc", "serve"]

  map:
    image: 3liz/qjazz:qgis-ltr-eager
    environment:
      CONF_LOGGING__LEVEL: debug
      CONF_BACKENDS__jOBS__TITLE: "Jobs backends"
      CONF_BACKENDS__JOBS__HOST: "qgis-rpc"
      CONF_BACKENDS__JOBS__ROUTE: "/results"
    ports:
    - 127.0.0.1:9080:9080
    command: ["qjazz-map", "serve"]

