services:
  qgis-rpc:
    image: 3liz/qjazz:qgis-release-eager
    environment:
      CONF_DISPLAY_XVFB: ON
      CONF_LOGGING__LEVEL: debug
      CONF_WORKER__NAME: worker
      CONF_WORKER__QGIS__PROJECTS__SEARCH_PATHS: >-
        { 
          "/": "/qgis-projects"
        }
    volumes:
    - { type: bind, source: "../../tests/data", target: /qgis-projects } 
    command: ["qjazz-rpc", "serve"]
  web:
    image: 3liz/qjazz:qgis-release-eager
    environment:
      CONF_LOGGING__LEVEL: debug
      CONF_SERVER__NUM_WORKERS: "2"
      CONF_BACKENDS__BASIC__TITLE: "Basic backends"
      CONF_BACKENDS__BASIC__HOST: "qgis-rpc"
      CONF_BACKENDS__BASIC__ROUTE: "/"  
    ports:
    - 127.0.0.1:9080:9080
    command: ["qjazz-map", "serve"]

