
# Minimal docker compose for running examples
services:
  worker:
    image: 3liz/jazz:qgis-release-eager
    working_dir: /opt/qjazz/python_modules/qjazz-processes
    command: qjazz-processes worker -C tests/worker-config.toml
    volumes:
    - { type: bind, source: "../../../", target: /opt/qjazz }
    profiles:
    - worker
    environment:
      CONF_WORKER__BROKER_HOST: rabbitmq
      CONF_WORKER__BACKEND_HOST: redis:6379/0
    depends_on: [rabbitmq, redis]
  rabbitmq:
    image: rabbitmq:3-management
  redis:
    image: redis:6-alpine
