

[logging]
level = "INFO"


[admin_http]
#
# Interfaces to listen to
listen = ["127.0.0.1",9871]
#
# Use ssl
use_ssl = false
#
# CORS origin
#
# Allows to specify origin for CORS. If set 'all' will set
# Access-Control-Allow-Origin to '*'; 'same-origin' return
# the same value as the 'Origin' request header.
# An url may may be specified, restricting allowed origin to this url.
cross_origin = "all"
#
# Enable proxy_configuration
#
# Indicates that the server is behind a reverse proxy.
# This enable handling of forwarded proxy headers
proxy_conf = false
#
# List of authorized tokens
auth_tokens = []

#
# TLS certificats
#
[admin_http.ssl]
#
# CA file
#cafile =   	# Optional
#
# TLS  certificat
#
# Path to the TLS cert file
#certfile =   	# Optional
#
# TLS key file
#
# Path to the TLS key file
#keyfile =   	# Optional


# Remote configuration settings
[admin_config_url]
#
# External configuration Url
#
# The server will issue a GET method against this url at startup.
# The method should returns a valid configuration fragment.
# Note that this overrides all local settings.
#url =   	# Optional

#
# TLS configuration
#
[admin_config_url.ssl]
#
# CA file
#cafile =   	# Optional
#
# TLS  certificat
#
# Path to the TLS cert file
#certfile =   	# Optional
#
# TLS key file
#
# Path to the TLS key file
#keyfile =   	# Optional


[resolvers]

#
# List of Rpc backends
#
[[resolvers.resolvers]]
#
# Unique label
#
# Unique resolver label. The label must be compatible with an url path component.
#label =   	# Required
#
# RPC address
address = ["::1",23456]
#
# Check for ipv6
ipv6 = false
#
# Use ssl connection
use_ssl = false
title = ""
#description =   	# Optional

#
# TLS certificats
#
[resolvers.resolvers.ssl]
#
# CA file
#cafile =   	# Optional
#
# TLS  certificat
#
# Path to the TLS cert file
#certfile =   	# Optional
#
# TLS key file
#
# Path to the TLS key file
#keyfile =   	# Optional

