version: "3.9"
services:

  qgis-rpc:
    image: 3liz/qgis-services:qgis-ltr-eager
    quenvironment:
      CONF_DISPLAY_XVFB: ON
      CONF_CONFIG_URL__URL: "http://config-server/qgis-rpc.json"
    volumes:
    - { type: bind, source: "../../tests/data", target: /qgis-projects } 
    command: ["qgis-server-rpc", "serve"]

  web:
    image: 3liz/qgis-services:qgis-ltr-eager
    environment:
      CONF_CONFIG_URL__URL: "http://config-server/web.json"
    ports:
    - 127.0.0.1:9080:9080
    command: ["qgis-server-http", "serve"]

  # The configuration server 
  config-server:
    image: nginx:alpine
    volumes:
    - type: bind
      source: "${PWD}/configs"
      target: /usr/share/nginx/html
      read_only: true

