version: "3.9"
services:

  qgis-rpc:
    image: 3liz/qjazz:qgis-ltr-eager
    environment:
      CONF_DISPLAY_XVFB: ON
      QJAZZ_REMOTE_CONFIG_URL: "http://config-server/qgis-rpc.json"
    volumes:
    - { type: bind, source: "../../tests/data", target: /qgis-projects } 
    command: ["qjazz-rpc", "serve"]

  web:
    image: 3liz/qjazz:qgis-ltr-eager
    environment:
      QJAZZ_REMOTE_CONFIG_URL: "http://config-server/web.json"
    ports:
    - 127.0.0.1:9080:9080
    command: ["qjazz-server-http", "serve"]

  # The configuration server 
  config-server:
    image: nginx:alpine
    volumes:
    - type: bind
      source: "${PWD}/configs"
      target: /usr/share/nginx/html
      read_only: true

